name: CoShulker
main: net.coreviabilisim.coshulker.CoShulkerPlugin
version: 1.0.0
api-version: "1.20"
authors: [esuhsy]
website: coreviabilisim.net
commands:
  cos:
    description: CoShulker ana komut.
    aliases: [coreviashulker]
    usage: "/cos help"
permissions:
  cos.use:
    description: Havada shulker acma izni.
    default: true
  cos.reload:
    description: Config yenileme izni.
    default: op
